#table(
  columns: 2,
  [*External Comments*], [*Response*],
  [Informal writing.],
  [The entire mini dissertation was read through once again the writing was changed any many places to sound more formal.],
  [Spelling and grammar errors highlighted],
  [Made the suggested changes and where necessary applied the change in other parts of the mini-dissertation],
  [Provide more descriptive captions for figures.],
  [Figure captions, especially for figures that show parameter variations in experiments should be read in conjunction with the text that references the set of figures to provide context. All figures are referenced in a corresponding paragraph.],
  [The claim in the abstract of “the proposed allocator consistently outperforms the default system allo-
  cators in both artificial and real world benchmarks” is too strong and needs to be softened.],
  [Made the suggested change.],
  [Include a bried disucssion about when a custom memory allocator would be useful],
  [Made the suggested change.],
  [Future work section is brief],
  [Merged future work section with conclusion and expanded it.],
  [It was not stated that the benchmarks were executed over multiple independent runs],
  [It is now mentioned that multiple independent runs were done.],
  [Fig 6.59 is not discussed.],
  [This mistake has been rectified.],
  [Section 5 proposes a memory allocator but not enough motivation is given for why it was designed as it was.],
  [A more comprehensive reasoning behind sub allocator choices has been added.],
    [In Section 6.1.2, can you be more specific about what “at random” means?],
  [This has been clarified.],
  [Due to layout of graphs the disucssion is hard to follow.],
  [The discussion has a better layout now making it easier to read and follow.],
  [Merge lists where it makes sense],
  [Made the suggested change.],
  [Too many subsections],
  [Sections have been removed and there are no longer unnecessary sub sections],
  [Pseudocode around Sec 5.1 would help in understanding the proposed allocator.],
  [Added pseudocode.],
  [More descriptive figure captions.],
  [Figures are referenced from the text where a detailed discussion for the figure is given],
  [Performing the experiments again but with the inclusion of the number of system calls would be useful.],
  [This is out of the scope of the project and this has now been added to the future work section.],
  [Different page sizes should be tested.],
  [This is out of scope as the memory allocator is designed for "out of the box usage" and this is not mentioned in the problem statement.],
  [Figure 6.60 does not make sense giving the previous experiments.],
  [Run more trials for the genetic program],
  [I believe this is because I failed to mention that each experiment was done over a number of independent runs which has now been recitified],
  [I disagree with this comment as Figure 6.60 shows the results of a real world algorithm whereas previous figures give results of synthetic benchmarks.
  You should use both synthetic and real-world benchmarks because they measure different aspects of performance. Synthetic benchmarks test specific components under controlled, ideal conditions and help identify theoretical limits, while real-world benchmarks measure how the software performs under realistic workloads with factors like caching, concurrency, I/O, and system interactions. The results can differ because synthetic tests simplify or isolate conditions, whereas real-world usage introduces variability and resource contention that affect actual performance.],
 
)
